"""FluxWall core package."""

from fluxwall.config import settings
from fluxwall.core.exporters import (
    HEIF_AVAILABLE,
    LivePhotoExporter,
    LivePhotoManifest,
    export_live_photo_bundle,
    export_mov,
    export_video,
    export_video_async,
    heic_to_jpeg,
    load_heic,
    save_heic,
)
from fluxwall.core.job_queue import (
    JobQueue,
    JobStatus,
    init_job_queue,
    job_queue,
    shutdown_job_queue,
)
from fluxwall.core.models import (
    IPHONE_RESOLUTIONS,
    ColorCycleParams,
    ExportFormat,
    ExportJob,
    ExportOptions,
    FlowingCurveParams,
    FrameArray,
    GameOfLifeParams,
    GeneratorParams,
    GeneratorType,
    JuliaParams,
    LSystemParams,
    MandelbrotParams,
    Preset,
    PreviewJob,
    iPhoneModel,
)
from fluxwall.core.presets import PresetRegistry, load_presets, preset_registry

__all__ = [
    'settings',
    'GeneratorParams',
    'GameOfLifeParams',
    'MandelbrotParams',
    'JuliaParams',
    'LSystemParams',
    'ColorCycleParams',
    'FlowingCurveParams',
    'GeneratorType',
    'ExportFormat',
    'iPhoneModel',
    'IPHONE_RESOLUTIONS',
    'Preset',
    'ExportOptions',
    'ExportJob',
    'PreviewJob',
    'FrameArray',
    'PresetRegistry',
    'preset_registry',
    'load_presets',
    'JobQueue',
    'job_queue',
    'init_job_queue',
    'shutdown_job_queue',
    'JobStatus',
    'export_video',
    'export_video_async',
    'export_mov',
    'save_heic',
    'load_heic',
    'heic_to_jpeg',
    'HEIF_AVAILABLE',
    'LivePhotoExporter',
    'LivePhotoManifest',
    'export_live_photo_bundle',
]
